MXNet Scala Benchmark AI support
leleamol/deep-learning-benchmark-mirror pull request #13
Opened 2018-05-24 00:23 UTC by lanking520

Add MXNet Scala portion on Benchmark AI
Contains Maven package and automated script.
Tested with 
```
python2 benchmark_driver.py --task-name scala_mxnet_cpu --num-gpus 0 --epochs 1
```
with Deep Learning AMI 9.0

2018-06-01 18:19 UTC, rajanksin requested changes

2018-06-01 18:19 UTC, spidyDev commented on task_config_template.cfg
> +[scala_mxnet_cpu]
Please add your tags to the end of file.

2018-06-01 23:05 UTC, lanking520 commented
Hi all,
I have test it through Dlbench and everything goes well:
Detail Status:
2018-06-01 13:39:42 --  Execution Started
2018-06-01 13:39:42 --  Entered State LaunchInstance
2018-06-01 13:39:42 --  Activity Scheduled
2018-06-01 13:40:07 --  Activity Started
2018-06-01 13:44:39 --  Activity Succeeded
2018-06-01 13:44:39 --  Exited State LaunchInstance --   Host IP: ec2-54-224-144-95.compute-1.amazonaws.com
2018-06-01 13:44:39 --  Entered State ConfigureInstance
2018-06-01 13:44:39 --  Activity Scheduled
2018-06-01 13:45:16 --  Activity Started
2018-06-01 13:46:29 --  Activity Succeeded
2018-06-01 13:46:29 --  Exited State ConfigureInstance --   Framework Version: mxnet-cu90 1.3.0b20180601
2018-06-01 13:46:29 --  Entered State RunBenchmark
2018-06-01 13:46:29 --  Activity Scheduled
2018-06-01 13:48:25 --  Activity Started
2018-06-01 13:59:08 --  Activity Succeeded
2018-06-01 13:59:08 --  Exited State RunBenchmark -- 
2018-06-01 13:59:08 --  Entered State TerminateInstance
2018-06-01 13:59:08 --  Activity Scheduled
2018-06-01 13:59:08 --  Activity Started
2018-06-01 13:59:09 --  Activity Succeeded
2018-06-01 13:59:09 --  Exited State TerminateInstance -- 
2018-06-01 13:59:09 --  Execution Succeeded

2018-10-19 23:22 UTC, lanking520 commented
Close this since Piyush get it done

2018-10-19 23:22 UTC, closed without merging